_wandb:
    value:
        cli_version: 0.22.2
        e:
            lsozd32f0je5akb1sw7k3b3p9fq5idda:
                args:
                    - --robot
                    - pi_plus
                    - --input_file
                    - source/motion/hightorque/pi_plus/csv/pi_plus_right_big_kick_cut.csv
                    - --input_fps
                    - "30"
                    - --output_name
                    - source/motion/hightorque/pi_plus/npz/kick1015.npz
                codePath: scripts/csv_to_npz.py
                codePathLocal: scripts/csv_to_npz.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "982820896768"
                        used: "409662173184"
                email: 2742974891@qq.com
                executable: /home/sunteng/miniconda3/envs/bydmimic/bin/python
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-d43cb428-abb2-9686-d48e-9ad33c6b22e0
                host: zixiang
                memory:
                    total: "33468534784"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/sunteng/beyondmimic/Pi_mimic_workshop-Pi_workshop_beyondmimic/scripts/csv_to_npz.py
                python: CPython 3.10.17
                root: /home/sunteng/beyondmimic/Pi_mimic_workshop-Pi_workshop_beyondmimic
                startedAt: "2025-10-15T03:47:45.113774Z"
                writerId: lsozd32f0je5akb1sw7k3b3p9fq5idda
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
            "4": 3.10.17
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
